name: SamRodd
favicon: null
layout_spectrum: 0.7519767256453633
typography_spectrum: 0.04158189776353538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8978908895514905
  lightness: 0.935379916569218
  saturation: 0.13089217874221504
  rhythmicContrast: 0.20211718860082328
purpose: []
